name: SuperMines
main: io.github.lijinhong11.supermines.SuperMines
version: ${project.version}
authors: ["mmmjjkx"]
description: A mine plugin
api-version: 1.20
folia-supported: true
website: https://github.com/LinsMinecraftStudio/SuperMines
libraries:
  - dev.triumphteam:triumph-gui:3.1.13
  - org.bstats:bstats-bukkit:3.1.0
depend:
  - CommandAPI
softdepend:
  - WorldEdit
  - FastAsyncWorldEdit
  - PlaceholderAPI
  - MiniPlaceholders
  - mcMMO
  - AuraSkills