name: SuperMines
main: io.github.lijinhong11.supermines.SuperMines
version: ${version}
authors: ["mmmjjkx"]
description: A mine plugin
api-version: "26.1"
folia-supported: true
website: https://github.com/LinsMinecraftStudio/SuperMines
depend:
  - MittelLib
softdepend:
  - ItemsAdder
  - Nexo
  - Oraxen
  - WorldEdit
  - FastAsyncWorldEdit
  - PlaceholderAPI
  - MiniPlaceholders
  - mcMMO
  - AuraSkills
