name: SuperMines
main: io.github.lijinhong11.supermines.SuperMines
version: ${project.version}
authors: ["mmmjjkx"]
description: A mine plugin
api-version: 1.20
folia-supported: true
website: https://github.com/LinsMinecraftStudio/SuperMines
depend:
  - CommandAPI
softdepend:
  - WorldEdit
  - FastAsyncWorldEdit
  - PlaceholderAPI
  - MiniPlaceholders
  - mcMMO
  - AuraSkills